# These are supported funding model platforms

github: andrea_mariadb, 777ninjamusic, andipandi111
patreon: andreamariadb
open_collective: andrea_mariadb
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: andrea_mariadb
issuehunt: andrea-mariadb
otechie: andrea_mariadb
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
